# Generates obj\AssemblyInfo.g.cs from the WSLTRAY_VERSION environment variable (default "dev").
# Run by build.cmd. The value is read from the environment here (never expanded by cmd.exe) and
# restricted to [0-9A-Za-z.+-] so it is safe to embed in a C# string literal.
param([Parameter(Mandatory = $true)][string]$Out)
$v = $env:WSLTRAY_VERSION
if ([string]::IsNullOrEmpty($v)) { $v = 'dev' }
if ($v.Length -gt 64 -or $v -notmatch '^[0-9A-Za-z.+-]+$') {
    [Console]::Error.WriteLine('ERROR: WSLTRAY_VERSION may only contain [0-9A-Za-z.+-] (max 64 chars), e.g. 0.1.1 or 0.2.0-rc1')
    exit 1
}
$num = '0.0.0.0'
if ($v -match '^(\d{1,5})\.(\d{1,5})\.(\d{1,5})([-+].*)?$') {
    if ([int]$Matches[1] -le 65534 -and [int]$Matches[2] -le 65534 -and [int]$Matches[3] -le 65534) {
        $num = ('{0}.{1}.{2}.0' -f [int]$Matches[1], [int]$Matches[2], [int]$Matches[3])
    }
}
$lines = @(
    '// generated by tools\mkver.ps1 - do not edit',
    ('[assembly: System.Reflection.AssemblyInformationalVersion("{0}")]' -f $v),
    ('[assembly: System.Reflection.AssemblyVersion("{0}")]' -f $num),
    ('[assembly: System.Reflection.AssemblyFileVersion("{0}")]' -f $num)
)
[System.IO.File]::WriteAllText($Out, ($lines -join "`r`n") + "`r`n", (New-Object System.Text.UTF8Encoding($false)))
Write-Host ('Version: ' + $v + ' (' + $num + ')')
